### ISSUE TITLE
Improve  the CSS of the page

### ISSUE THREAD

**Issue by ayush8010720467** [ayush8010720467/web_whiteboard#11]

**Comment by SaintJul** [comment]
How can I help.

**Comment by ayush8010720467** [comment]
Please attach the screenshot of the visual changes made.

**Comment by soujo** [comment]
HI @ayush8010720467, could you kindly elaborate more on how would you like to improve the CSS ?
Do you have some predefined color theme in your mind? If yes then please share.
I am interested to contribute to this issue, kindly assign it to me.

**Comment by ayush8010720467** [comment]
Hi @soujo I Don't have any predefined color theme right now. But the color shades should include majorly black and white.

**Comment by soujo** [comment]
Thank you for assigning me this issue. 
I will keep the color shades in mind and will present the output tomorrow for your review.
